name: Deploy MkDocs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
      
      - name: Install Pillow and CairoSVG
        run: pip install pillow cairosvg
      
      - name: Install dependencies
        run: pip install -r requirements-doc.txt
      
      - name: Build and deploy MkDocs
        run: |
          mkdocs gh-deploy
